name: Deploy to S3

on:
  push:
    branches:
    - prod

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to s3
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
      run: |
        aws s3 sync s3://global-maintenance-page